---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: ${MOLECULE_DISTRO:-ubuntu2204}
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: profile_tasks, timer, yaml
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
